### ISSUE TITLE
TODO Implement increment and decrement method

### ISSUE THREAD

**Issue by neradp** [pd4d10/memcached-cli#2]
uncoment:
` increment: 'increment',
   decrement: 'decrement',`

and fix:
`// key, amount, expires(optional)
    case 'increment':
    case 'decrement':
      return {
        command: `${method} <key> <amount> [expires]`,
        query: args => cb =>
          client[method](
            args.key.toString(),
            args.amount.toString(),
            {'expires': Number(args.expires) || 0},
            cb,
          ), // eslint-disable-line
      }`

After this code changes increment and decrement commands works like a charm

**Comment by pd4d10** [comment]
Thanks! Willing to submit a PR?

**Comment by neradp** [comment]
Ok i do some PRs 👍

**Comment by pd4d10** [comment]
Published as v1.0.3. Thanks!
